name = "search"
type = "javascript"
account_id = 'a621ef82bdece5f0c973bd445080bf27'
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
